# ======================================================
# Site settings
# ======================================================
title: ""
description: "PhD Researcher in Sociology"
url: "https://anninacla.github.io"
baseurl: ""  # user site

# ======================================================
# Author info
# ======================================================
author:
  name: "Annina Claesson"
  avatar: "images/ac-ScPo-2022.jpg"   # avatar image in /images/
  bio: "PhD Candidate in Sociology at Sciences Po, focusing on social media and public figures"
  email: "annina.claesson@sciencespo.fr"
  github: "anninacla"
  scholar: "lYqPQXMAAAAJ"
  bluesky: "anninac.bsky.social"

# ======================================================
# Theme
# ======================================================
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# ======================================================
# Plugins
# ======================================================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# ======================================================
# Navigation menu
# ======================================================
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/

# ======================================================
# Collections
# ======================================================
collections:
  publications:
    output: true
    permalink: /publications/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

# ======================================================
# Defaults for layouts
# ======================================================
defaults:
  # Pages inside /pages/
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: single
      author_profile: true

  # Home page
  - scope:
      path: "pages/index.md"
      type: "pages"
    values:
      layout: home
      author_profile: true

  # Publications collection
  - scope:
      path: ""
      type: "publications"
    values:
      layout: single
      author_profile: false

  # Teaching collection
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: single
      author_profile: false

# ======================================================
# Markdown settings
# ======================================================
markdown: kramdown
highlighter: rouge

