title: Annina Claesson
description: PhD Researcher
remote_theme: pages-themes/minimal@v0.2.0  # simple, built-in-compatible theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
url: "https://anninacla.github.io"
author: Annina Claesson

nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Publications
    link: /publications
  - name: Teaching
    link: /teaching
