# ======================================================
# Site settings
# ======================================================
title: ""
description: "PhD Researcher in Sociology"
url: "https://anninacla.github.io"
baseurl: ""  # user site

# ======================================================
# Author info
# ======================================================
author:
  name: "Annina Claesson"
  avatar: "images/ac-ScPo-2022.jpg"
  bio: "PhD Candidate - CREST & Sciences Po médialab"
  email: "annina.claesson@sciencespo.fr"
  links:
    - label: "GitHub"
      url: "https://github.com/anninacla"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=lYqPQXMAAAAJ"
    - label: "Bluesky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/anninac.bsky.social"

# ======================================================
# Theme
# ======================================================
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# ======================================================
# Plugins
# ======================================================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# ======================================================
# Navigation menu
# ======================================================
navigation:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/

# ======================================================
# Defaults for layouts
# ======================================================
defaults:
  # Pages inside /pages/
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: single
      author_profile: true  # Changed to false to remove sidebar on pages

